### ISSUE TITLE
Render popper element based on condition

### ISSUE THREAD

**Issue by bnachtweh** [valgeirb/vue3-popper#1]
Hi! First of all; great job writing this very easy to use popper component! 

I would like to request a feature regarding conditional rendering. I have the following scenario:

```
<template>
  <Popper arrow hover>
    <button> hover me! </button>
    <template #content v-if="condition ">
      Show popper only when condition is met
    </template>
  </Popper>
</template>
```

### Shown result

I get an empty popper element on hover, due to the fact that I conditionally render the content template. 

### Expected result

I can pass a `show` prop to the `Popper` component, or the `popperNode` checks if the content slot is defined: https://github.com/valgeirb/vue3-popper/blob/main/src/component/Popper.vue#L18

I would like the popper element to not be rendered / shown when I explicitly say so. It can be visible by default (implicitly) of course.

**Comment by valgeirb** [comment]
Thank you! This is a good improvement, I'll look into it and will let you know 👍🏻 

Do you have any opinion on what is the cleaner API? Passing a "visible/show" prop vs. just checking the content slot internally?

**Comment by bnachtweh** [comment]
Maybe both is fine, just like you suggested. There can be instances where you would like to show the tooltip based on timing or by default, without any interaction. Anyway, it improves code readability when you can utilize a `show` property  and the v-if looks like a sensible addition, as it's seems unnecessary to render an empty tooltip component.

**Comment by valgeirb** [comment]
I fixed the `v-if` bug and then realized I didn't fully grasp your issue, you want full manual control over the visibility of the Popper right?

**Comment by bnachtweh** [comment]
I saw your update, thanks! A `show` property would give more control and could be useful in some situations, but maybe we could create a separate issue if this feature is desired.
