### ISSUE TITLE
Keeping popper open while hovering over it

### ISSUE THREAD

**Issue by thebreadlord** [valgeirb/vue3-popper#11]
Hey, I love what you've got so far!  I do have a specific need though for our client and I was going to see if you could help me out?  Basically, when using the "hover" option for the Popper, we would like to keep the popper open as long as the user is hovering over either the trigger element or the popper itself.  We are using this to provide a user some options (with buttons for confirming/rejecting and such) when hovering over certain elements.  Is there any way we can make that happen?  I'd appreciate it, and thanks for your time!

**Comment by valgeirb** [comment]
Thank you for this improvement idea, just released [a new version for you](https://github.com/valgeirb/vue3-popper/releases/tag/v0.6.0).

**Comment by thebreadlord** [comment]
This is great, thank you so much! Works great but I may have noticed a small bug.  It seems to work fine for all the positions except for bottom.  When I hover over a bottom popper it loses visibility when leaving the target element.  Is that an issue on my end or do you see the same thing?

**Comment by valgeirb** [comment]
@thebreadlord I can't seem to reproduce the bug, it still might be a bug! Can you reproduce it?

![hover](https://user-images.githubusercontent.com/2593027/125792135-a5d4b48a-4204-450a-8e96-a39fdb21d611.gif)

**Comment by thebreadlord** [comment]
Hey thanks for looking into it.  There might be a css issue on our site causing a conflict, but our "style guy" is out of town.  I'll poke at this a bit more and get in touch with you if I find some better details.  Really appreciate all the support on this so far!  Keep up the great work
