### ISSUE TITLE
Keep popper open on hover 

### ISSUE THREAD

**Issue by michaelscraft** [valgeirb/vue3-popper#19]
Is there a way to keep popper open after user hovers on the trigger(for nav dropdown purposes)?

**Comment by valgeirb** [comment]
@michaelscraft Did you update your vue3-popper dependency to fix your problem or is this perhaps a bug?

**Comment by michaelscraft** [comment]
Yep, after updating from 0.4 to 1.0.2 everything works great. Thank you for this library 🙌. Looking forward to manually control when to show popper.

**Comment by valgeirb** [comment]
I just added a `show` prop for manual control in [v1.1.0](https://github.com/valgeirb/vue3-popper/releases/tag/v1.1.0)
