### ISSUE TITLE
add typescript declaration file?

### ISSUE THREAD

**Issue by littlecxm** [valgeirb/vue3-popper#20]
it will perfect if add it :)

**Comment by valgeirb** [comment]
Will look into this...

**Comment by satanshiro** [comment]
to compile without official typings put this
in a d.ts file in src folder

```
declare module "vue3-popper" {
    const file: Component;

    export default file;
}
```

and in main.ts
```
import Popper from "vue3-popper";
app.component('Popper', Popper);
```

**Comment by NatanCieplinski** [comment]
> Will look into this.

Did you already started on it? I'm looking in sharpening my ts skills and if you don't mind i would like to work on this enhancement

**Comment by ngocsangyem** [comment]
Try this [vue-use-popperjs](https://iendeavor.github.io/vue-use-popperjs/playground.html)  wrapper popperjs. It also supports typescript. @NatanCieplinski

**Comment by valgeirb** [comment]
@NatanCieplinski sorry for the delay, this has been added in v1.5.0
