### ISSUE TITLE
There is no style

### ISSUE THREAD

**Issue by kasp3rsky** [valgeirb/vue3-popper#22]
Hi, I installed popper and there is no style. Version is 1.1.0. Any suggestion?

**Comment by valgeirb** [comment]
Did you read the [styles documentation](https://valgeirb.github.io/vue3-popper/guide/getting-started.html#what-about-styles)?

Maybe I should add some default styles, but for now you need to overwrite the CSS vars.

**Comment by valgeirb** [comment]
You probably need to read the docs and set your CSS vars. Feel free to reach out if you need help.
