### ISSUE TITLE
Rendered content

### ISSUE THREAD

**Issue by AubSs** [valgeirb/vue3-popper#23]
Hi! First, thank you for your great lib!

When we render a lot of popper, the browser will drastically slow down (due to popper.js)
Do you know how to render the popper on the fly ?
Or a way to render the content only when the selector is hovered ?

Thx you!

**Comment by valgeirb** [comment]
This might be related to #13 - I'll take a look at this and see if I can improve performance, thank you!

**Comment by valgeirb** [comment]
How many Poppers are we talking about here?

**Comment by AubSs** [comment]
Not sure it's the same use case, but we both struggle with performance issues

**Comment by AubSs** [comment]
> 150 slow down, but usable
> 500, unusable

Sometime we cannot use virtual-list, and we need to render more than 300 elements and each can have 10 popper...

**Comment by nikkwong** [comment]
Is there a reason that the library doesn't just detach it from the dom using `v-if` (or similar strategy)?

**Comment by valgeirb** [comment]
> Is there a reason that the library doesn't just detach it from the dom using `v-if` (or similar strategy)?

I'm using the default slot to display whatever Popper is wrapping so I don't think I can do that, I could look into [disabling event listeners](https://popper.js.org/docs/v2/tutorial/#performance), maybe that would help.
