### ISSUE TITLE
[Bug Report] The `zIndex` prop seems not working

### ISSUE THREAD

**Issue by ddzy** [valgeirb/vue3-popper#26]
## Current behavior

![image](https://user-images.githubusercontent.com/33921398/127244159-9c177e63-87ce-44c1-a6e9-274665ed0107.png)

related issues: #24 

## Expected behavior

`zIndex` should be add into popper element's style

![image](https://user-images.githubusercontent.com/33921398/127244510-65828213-92e2-4479-bf95-0da8c5ea40f7.png)

**Comment by valgeirb** [comment]
Maybe I'm missing something obvious, but it seems to be working for me - the `popper div` gets the z-index property that you pass in as a prop.

Can you help me with this?

![Popper](https://user-images.githubusercontent.com/2593027/127292599-46b71d49-a8b4-4550-aaf8-8a7448cc8bf7.png)
![devtools](https://user-images.githubusercontent.com/2593027/127292617-b53eded5-1f5e-4d1d-a3ed-cfd20b6ce913.png)

**Comment by ddzy** [comment]
I think the problem maybe caused by css's priority🤔:

- Passing the `zIndex` property  to `Popper` component directly(**not working**)
- In my browser, add the `z-index` css propery into `popper div`'s inline stylesheet manually(**working well**)

**Comment by valgeirb** [comment]
> * Passing the `zIndex` property  to `Popper` component directly(**not working**)

This is weird since that works for me, can you create a reproduction of this somehow with CodeSandbox?

I made an example as well, can you please [check it out](https://codesandbox.io/s/affectionate-pike-lsk08) and compare it to your code?  

Also, if you don't use the `zIndex` prop (just skip it), the default `z-index` should default to 9999 - can you check if that works?

**Comment by VyazovskyE** [comment]
I have same bug.
![image](https://user-images.githubusercontent.com/51908480/127318461-79c41d4e-1733-4fe6-8a39-33d562a4c1e4.png)
![image](https://user-images.githubusercontent.com/51908480/127318560-879afc52-a704-468a-be5e-1fc16dd7722e.png)
There is no property with css variable when i pass prop.
But i don't need dynamic z-index so i just fix it with css rule
![image](https://user-images.githubusercontent.com/51908480/127318863-1e919f48-40a6-484c-9382-f902b050a75e.png)

**Comment by valgeirb** [comment]
What version of Vue are you using? Can you try updating to v3.1.5 and see if that does anything for you? 

I'm using the [SFC style variables](https://github.com/vuejs/rfcs/blob/master/active-rfcs/0043-sfc-style-variables.md) for this feature and I might need to back away from that.

**Comment by VyazovskyE** [comment]
Probably thats a problem, im running vue v3.0.4

**Comment by valgeirb** [comment]
@ddzy please try updating Vue to v3.1.5

**Comment by ddzy** [comment]
> @ddzy please try updating Vue to v3.1.5

TKS, upgrade vue from `3.0.5` to `3.1.5` solved my problem.

![image](https://user-images.githubusercontent.com/33921398/127413407-119f50db-55df-445f-b4a9-4c5688c75d49.png)

![image](https://user-images.githubusercontent.com/33921398/127413432-7248d2e9-026e-4038-8c01-881facab3104.png)
