### ISSUE TITLE
Possible on click modifiers?

### ISSUE THREAD

**Issue by Mootook** [valgeirb/vue3-popper#28]
Hello!

I've been using this package in my team's application recently. Thanks for it, it's really convenient.
This is mainly a feature request for adding click modifiers onto the `triggerNode`.
Sometimes I have the triggerNode embedded in a div and would like to make sure that clicking on the trigger node doesn't fire any events for its containing element (such as with `click.stop` on the child).

This opened up the possibility of using the manual controls exposed by vue3-popper, but I'd lose a lot of the built in convenience of using this as a wrapper for all of my app's popovers (click away, for example).

Thanks for the work!

**Comment by valgeirb** [comment]
Could you provide a reproduction?

I think I might have an idea of what you mean but it would be good to see exactly.

**Comment by valgeirb** [comment]
I need a reproduction to be able to help you.
