### ISSUE TITLE
let content know if open

### ISSUE THREAD

**Issue by mech01nc01** [valgeirb/vue3-popper#3]
hey great work!
i'm just switching to vue 3 and used vue-tippy before

what i'm struggling with:

situation 1:
often i load more content from server when tippy is shown. i COULD solve this with the show-event but its really dirty ^^
it would be nice if i nut just could "import" the close-function, but also isOpen
example: <template #content="{close, isOpen}"><component :load="isOpen" /></tmeplate>

if this would be possible i could conditionally decide what to render and trigger what to fetch for the server

situation 2:
is it possible to use 1 popper for multiple elements? in vue-tippy i could use :to="element" to change the element where the popper was bound to
why: in a table with 100 rows and 3 columns where every column has a popper, this would be 300 poppers
nice would be to have 3 popper, one for each column and when i hover over a table-cell i will change a variable so the content within the popper can update
is that possible?

**Comment by valgeirb** [comment]
Thank you for these suggestions, I'll look into this ASAP and get back to you 👍

**Comment by valgeirb** [comment]
For situation 1: 

If I provide `isOpen` through the scoped slot, would that be enough for you (remember it is not mutable)? If you could provide a code example of what you want to do that would be great.

For situation 2:

It is not possible at the moment, it seems like a good idea for performance maybe? I'm going to experiment with this.

**Comment by mech01nc01** [comment]
situation 1:

possible usecase 1:

``` html
<template>
  <Popper>
    <Button>Demo</Button>
    <template #content="{ isOPoen }">
      <myComponent v-if="isOPen" :id-for-loading-additional-content="myId" /> <!-- myComponent will we loaded every time the popper is opened, maybe the most performant way as situation 2 is not possible at the moment, though it has to fetch the data every time the popper will open, but with a delay thats ok !-->
    </template>
  </Popper>
</template>
```

possible usecase 2:

``` html
<template>
  <Popper>
    <Button>Demo</Button>
    <template #content="{ isOPoen }">
      <myComponent :load="isOPen" :id-for-loading-additional-content="myId" /> <!-- myComponent will we loaded even if the popper will open or not, but the component can watch for 'load' and if load changes myComponent can fetch the the additional data. it may refresh the data if load changes a second time OR just do nothin and use cached data !-->
    </template>
  </Popper>
</template>
```

**Comment by valgeirb** [comment]
@mech01nc01 I've published a prerelease version for the `isOpen` functionality, you can install it with 

`npm i vue3-popper@unstable`

Could you try it out for me and see if it works for you?

**Comment by valgeirb** [comment]
Closing this issue with #12 and will continue in #13

**Comment by mech01nc01** [comment]
hey thanks for your work!

it seems to work, could not test it completely till now because we are still migrating to vue3, but it lookspromising, thank you very much!
