### ISSUE TITLE
Appears to Apply Styling to the Attached Element

### ISSUE THREAD

**Issue by B1ue-W01f** [valgeirb/vue3-popper#30]
Apologies if I'm getting this wrong, but it appears to apply styling to the element the popper is attached to:

```
element.style {
    border: 12px solid transparent;
    margin: -12px;
    --23121010: 9999;
}
```

I would suggest styling of the attached element is removed and left to the user.

**Comment by valgeirb** [comment]
I add these styles (`border`, `margin`) if the Popper is `interactive` so that it won't close when for example, hovering from the trigger element to the Popper itself. 

Is this causing problems?

**Comment by valgeirb** [comment]
Closing this since this is intentional, please let me know if this is causing you any problems.

**Comment by JapSeyz** [comment]
This seems to be causing problems, namely https://github.com/valgeirb/vue3-popper/issues/69 and https://github.com/valgeirb/vue3-popper/issues/45 and https://github.com/valgeirb/vue3-popper/issues/50

(For me as well, which is why I am looking into how to disable this)

**Comment by prattcmp** [comment]
To fix right margin being too small, I've had to append the following to every `<Popper>` instance: `style="width: calc(100% + 12px);"`
