### ISSUE TITLE
'Close' slot property is undefined

### ISSUE THREAD

**Issue by 0leg53** [valgeirb/vue3-popper#4]
'close' slot property is undefined on popover showing, it's okay to add some checking like
```
    if (popover && popover.close) {
      popover.close();
    }
```
Also problem can be looked at [demo page](https://valgeirb.github.io/vue3-popper/guide/getting-started.html#using-scoped-slot-properties).

Error text is 
> TypeError: Cannot destructure property 'close' of 'undefined' as it is undefined.

**Comment by valgeirb** [comment]
Sorry about this, will fix ASAP.
