### ISSUE TITLE
Don't use directives

### ISSUE THREAD

**Issue by xvaara** [valgeirb/vue3-popper#41]
You should remove the usage of directives and use composable for click away... for example: https://vueuse.org/core/onClickOutside/

They aren't working in SSR apps, and require custom transformers in build tools.

Vue documentation says:
> We recommend to prefer using components as the abstraction mechanism instead of directives.

**Comment by valgeirb** [comment]
Done in [v1.4.0](https://github.com/valgeirb/vue3-popper/releases/tag/v1.4.0)
