### ISSUE TITLE
Pass custom modifiers

### ISSUE THREAD

**Issue by neoighodaro** [valgeirb/vue3-popper#47]
**Description of the bug**
I would like to pass [custom modifiers](https://popper.js.org/docs/v2/constructors/#options) but there seems to be no way to do this using this package? Maybe you have some ideas? Or maybe I missed something.

**Expected behavior**
Should be able to modify the Popper instance directly to override the default options

**Comment by j4kim** [comment]
@neoighodaro is this a feature now ? I can't find the option
