### ISSUE TITLE
Crashes after upgrading vue3-popper to anything above 1.2.1

### ISSUE THREAD

**Issue by thebreadlord** [valgeirb/vue3-popper#48]
Hey, I've been using your popper component for a long time now, but I tried upgrading to the newest version today in hopes to resolve an issue I'm having, but I am getting a crash anytime I upgrade to a version higher than 1.2.1.  I was on 1.1.0 previously.  I did a few installs one version at a time and found that everything runs ok for 1.1.0, 1.2.0 and 1.2.1.  But anything higher than that and I get the following runtime crash...

I don't see any open issues related to this, so I wanted to get your input, if you have the time.  Anything that immediately comes to mind that I might be missing?  Thanks!

![Screenshot 2021-12-16 03 29 15](https://user-images.githubusercontent.com/80926887/146358797-45d3136e-98e7-4969-b5f6-427035feaada.png)

**Comment by valgeirb** [comment]
What version of Vue are you using? Can you try updating to vue@3.2.x and see if that solves your problem?

**Comment by thebreadlord** [comment]
I will be checking that out today, thanks. Our client’s application is still using a 3.0 build. It needs to be upgraded to 3.2, I just have to fight a battle with management about the upgrade and the regression testing. I’m sure you know the drill. But I’ll keep you posted, I’m sure that’s the problem. Thanks!

**Comment by thebreadlord** [comment]
Ok I apologize for the delay getting back to you, holidays hit and then I got pulled over to some other tasks and couldn't test this out until today.  Looks like Vue 3.2 does fix that crash I was receiving, so I think we're fine to close this issue, thanks, appreciate it man

**Comment by valgeirb** [comment]
No worries, thanks for letting me know 👍
