### ISSUE TITLE
Nuxt3 throws "window is not defined" error in SSR context

### ISSUE THREAD

**Issue by thplat** [valgeirb/vue3-popper#57]
**Description of the bug**
In Nuxt3 the `useClickAway` composable throws an error within an SSR context: `window is not defined`. 

The error occurs here:

```
  if (!window) {
    return;
  }
```
however I have no idea why Nuxt complains here since the expression `!window` should just evaluate to a thruthy value and therefore just process the if-statement.

The following will fix the issue:

```
  if (typeof window !== 'undefined' || !window) {
    return;
  }
```

I will submit a PR

**Comment by valgeirb** [comment]
Fixed in v1.4.2
